name: PortalNetwork
on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}/packages/portalnetwork

defaults:
  run:
    working-directory: packages/portalnetwork

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-unit-portalnetwork:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Remove unused packages from package.json
        uses: sergeysova/jq-action@v2
        working-directory: ${{ github.workspace }}
        with:
          cmd: "jq -r '.workspaces |= .[0:2]' package.json > package.json"
      
      - name: Show package.json
        run: cat package.json
        working-directory: ${{ github.workspace }}


      - name: Test output
        run: echo ${{ steps.vars.outputs.package }}
        working-directory: ${{ github.workspace }}

      - run: npm i
        working-directory: ${{ github.workspace }}

      - run: npm run lint
      - run: npm run test

  test-integration-portalnetwork:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i
        working-directory: ${{ github.workspace }}

      - run: npm run tape -- 'test/integration/wire.spec.ts'    

  
