name: PortalNetwork
on:
  push:
    branches: [master, add-CI-for-tests]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}/packages/portalnetwork

defaults:
  run:
    working-directory: packages/portalnetwork

jobs:
  test-portalnetwork:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Use npm v7 for workspaces support
        run: npm i -g npm@7

      - run: npm i 
        working-directory: ${{ github.workspace }}

      - run: npm run test
